import esbuild from "esbuild";
import { readFile, writeFile } from "node:fs/promises";
import process from "node:process";
import builtins from "builtin-modules";

const watch = process.argv.includes("--watch");
const verifyIndex = process.argv.indexOf("--verify");
const verifyReference =
  verifyIndex === -1 ? null : process.argv[verifyIndex + 1] || "release/iconfine/iconfine.css";

const ICON_PACK_IDS = ["lucide", "tabler", "tabler-filled"];

function parseMappings(css, pattern, packName) {
  const mappings = new Map();

  for (const match of css.matchAll(pattern)) {
    mappings.set(match[1], match[2]);
  }

  if (mappings.size === 0) {
    throw new Error(`No ${packName} icon mappings were found`);
  }

  return [...mappings.entries()]
    .map(([id, codepoint]) => ({ id, codepoint }))
    .sort((a, b) => a.id.localeCompare(b.id));
}

const lucideCss = await readFile("lucide.css", "utf8");
const tablerCss = await readFile("tabler-icon/tabler-icons.css", "utf8");
const tablerFilledCss = await readFile("tabler-icon/tabler-icons-filled.css", "utf8");

const lucideIcons = parseMappings(
  lucideCss,
  /\.icon-([a-z0-9-]+)::before\s*\{\s*content:\s*"\\([a-f0-9]+)";\s*\}/gi,
  "Lucide",
);
const tablerIcons = parseMappings(
  tablerCss,
  /\.ti-([a-z0-9-]+):before\s*\{\s*content:\s*"\\([a-f0-9]+)";\s*\}/gi,
  "Tabler",
);
const tablerFilledIcons = parseMappings(
  tablerFilledCss,
  /\.ti-([a-z0-9-]+):before\s*\{\s*content:\s*"\\([a-f0-9]+)";\s*\}/gi,
  "Tabler Filled",
);

const icons = {
  lucide: lucideIcons,
  tabler: tablerIcons,
  "tabler-filled": tablerFilledIcons,
};

const generatedTs = `export interface IconDefinition {\n  id: string;\n  codepoint: string;\n}\n\nexport const LUCIDE_ICONS: IconDefinition[] = ${JSON.stringify(lucideIcons, null, 2)};\n\nexport const TABLER_ICONS: IconDefinition[] = ${JSON.stringify(tablerIcons, null, 2)};\n\nexport const TABLER_FILLED_ICONS: IconDefinition[] = ${JSON.stringify(tablerFilledIcons, null, 2)};\n`;
await writeFile("src/icons.generated.ts", generatedTs, "utf8");

const baseCss = await readFile("src/styles-base.css", "utf8");
await writeFile("styles.css", `${baseCss.trim()}\n`, "utf8");

// The plugin ships its own fonts, so they are embedded once as data URLs and
// reused for both the FontFace screen fonts and the generated CSS snippet.
const fontDataUrls = {};
for (const [packId, source] of [
  ["lucide", "lucide.woff2"],
  ["tabler", "tabler-icon/tabler-icons.woff2"],
  ["tabler-filled", "tabler-icon/tabler-icons-filled.woff2"],
]) {
  fontDataUrls[packId] = `data:font/woff2;base64,${(await readFile(source)).toString("base64")}`;
}

// The snippet keeps the `url("iconfine-*.woff2")` placeholders; the plugin
// swaps them for the embedded fonts above, so the payload is stored once.
const rendererBaseCss = await readFile("src/renderer-base.css", "utf8");

const embeddedTs = `// Generated by build.mjs. Do not edit by hand.\nexport type IconfineFontPackId = "lucide" | "tabler" | "tabler-filled";\n\nexport const ICONFINE_FONT_DATA_URLS: Record<IconfineFontPackId, string> = ${JSON.stringify(fontDataUrls, null, 2)};\n\nexport const ICONFINE_SNIPPET_BASE_CSS = ${JSON.stringify(rendererBaseCss)};\n`;
await writeFile("src/embedded.generated.ts", embeddedTs, "utf8");

if (verifyReference) {
  await esbuild.build({
    entryPoints: ["src/snippet-css.ts"],
    bundle: true,
    format: "esm",
    target: "es2018",
    logLevel: "silent",
    outfile: "temp/snippet-css.mjs",
  });
  const { buildIconfineSnippetCss } = await import(
    new URL("./temp/snippet-css.mjs", `file://${process.cwd()}/`).href
  );
  const runtimeCss = buildIconfineSnippetCss({
    baseCss: rendererBaseCss,
    fontDataUrls,
    packs: icons,
  });
  const referenceCss = await readFile(verifyReference, "utf8");
  const verdict =
    runtimeCss === referenceCss
      ? `PASS: runtime snippet CSS matches ${verifyReference} (${runtimeCss.length} bytes)`
      : `FAIL: runtime ${runtimeCss.length} bytes vs reference ${referenceCss.length} bytes`;
  console.log(verdict);
  if (runtimeCss !== referenceCss) {
    const index = [...runtimeCss].findIndex((char, i) => char !== referenceCss[i]);
    console.log(`First difference near:\n${runtimeCss.slice(Math.max(0, index - 120), index + 120)}`);
    process.exitCode = 1;
  }
}

const context = await esbuild.context({
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: ["obsidian", "electron", "@codemirror/autocomplete", "@codemirror/collab", "@codemirror/commands", "@codemirror/language", "@codemirror/lint", "@codemirror/search", "@codemirror/state", "@codemirror/view", "@lezer/common", "@lezer/highlight", "@lezer/lr", ...builtins],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: watch ? "inline" : false,
  treeShaking: true,
  outfile: "main.js",
});

if (watch) {
  await context.watch();
  console.log(`Iconfine: watching ${ICON_PACK_IDS.map((id) => `${icons[id].length} ${id}`).join(", ")}`);
} else {
  await context.rebuild();
  await context.dispose();
  console.log(`Iconfine: built ${lucideIcons.length} Lucide, ${tablerIcons.length} Tabler, and ${tablerFilledIcons.length} Filled icons`);
}
